Create procedure sp_AddListing       
(       
		@Title varchar,
		@Address varchar,
		@City varchar,
		@State varchar,
		@ZipCode varchar,
		@Description varchar,
		@Price decimal,
		@Bedrooms int,
		@Bathrooms int,
		@Garage int,
		@Sqft int,
		@LotSize decimal,
		@PhotoMain varchar,
		@Photo1 varchar = 'N/A',
		@Photo2 varchar = 'N/A',
		@Photo3 varchar = 'N/A',
		@Photo4 varchar = 'N/A',
		@Photo5 varchar = 'N/A',
		@Photo6 varchar = 'N/A',
		@IsPublished bit,
		@ListDate datetime,
		@RealtorId int
)      
As       
Begin       
    Insert into dbo.Listings (
		Title,
		Address,
		City,
		State,
		ZipCode,
		Description,
		Price,
		Bedrooms,
		Bathrooms,
		Garage,
		Sqft,
		LotSize,
		PhotoMain,
		Photo1,
		Photo2,
		Photo3,
		Photo4,
		Photo5,
		Photo6,
		IsPublished,
		ListDate,
		RealtorId)
		
    Values (
		@Title,
		@Address,
		@City,
		@State,
		@ZipCode,
		@Description,
		@Price,
		@Bedrooms,
		@Bathrooms,
		@Garage,
		@Sqft,
		@LotSize,
		@PhotoMain,
		@Photo1,
		@Photo2,
		@Photo3,
		@Photo4,
		@Photo5,
		@Photo6,
		@IsPublished,
		@ListDate,
		@RealtorId)       
End